# Generated by Django 5.2 on 2025-05-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="popdate",
            new_name="pubdate",
        ),
    ]
