# Generated by Django 5.2 on 2025-07-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_article_og_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="summary",
            field=models.CharField(),
        ),
    ]
